#!/bin/bash

SCRIPT_NAME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

TARGET_DIR="$1"

if is empty "$TARGET_DIR"; then
  echo "Usage: $SCRIPT_NAME target_dir file_1 [file_2]..[file_n]"
  exit
fi

shift 1

for FILE in "$@"; do
    abook-long-split "$FILE" "$TARGET_DIR"
done
