#!/bin/bash

# https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
set -o errexit
set -o functrace
set -o nounset

SCRIPTS="$HOME/scripts"
SCRIPT_RHVOICE_FIXED="$SCRIPTS/rhvoice-fixed.sh"
SCRIPT_RHVOICE_FIX_FILE="$SCRIPTS/rhvoice-fix-file.sh"

if [ "$#" -lt 1 ]; then
  echo "Usage: abook-speed SOURCE [SPEED_MULTIPLIER]"
  echo
  echo "  SPEED_MULTIPLIER: 1.4 by default"
  exit
fi

function parse_extension { FILE_NAME_WITH_EXT="$1"
  echo "$FILE_NAME_WITH_EXT" | rev | cut -f 1 -d '.' | rev
}

function parse_file_name_no_ext { FILE_NAME_WITH_EXT="$1"
  EXTENSION=$(parse_extension "$FILE_NAME_WITH_EXT")
  #echo "DEBUG: parse_file_name_no_ext: EXTENSION: $EXTENSION"
  echo "$FILE_NAME_WITH_EXT" | sed -e s/\.${EXTENSION}$//g
}

set +o nounset
SOURCE_PATH="$1"
SPEED_MULTIPLIER="$2"
set -o nounset

if [ -z "$SPEED_MULTIPLIER" ]; then
  SPEED_MULTIPLIER=1.4
fi

SOURCE_EXT=$(parse_extension "$SOURCE_PATH")
SOURCE_PATH_NO_EXT=$(parse_file_name_no_ext "$SOURCE_PATH")
DEST_PATH="${SOURCE_PATH_NO_EXT}__${SPEED_MULTIPLIER}x.mp3"

(
  set -x;
  sox "$SOURCE_PATH" "$DEST_PATH" tempo "$SPEED_MULTIPLIER"
)
