#!/bin/bash

# `sudo apt install mp3splt` required before first run

SPLIT_BY_MINUTES_DEFAULT=10
SPLIT_FOLDER_NAME=split

echo "$1"
echo "$2"

FILE_REL_PATH="$1"

if [[ -z "$FILE_REL_PATH" ]]; then
  echo "Mp3 file name required"
  exit
fi

SPLIT_BY_MINUTES=$2

if [[ -z "$SPLIT_BY_MINUTES" ]]; then
  SPLIT_BY_MINUTES=$SPLIT_BY_MINUTES_DEFAULT
fi

FILE_DIR_PATH=$(dirname "$FILE_REL_PATH")
FILE_NAME_WITH_EXT=$(basename "$FILE_REL_PATH")

#FILE_EXTENSION="${FILE_NAME_WITH_EXT#*.}"
#FILE_NAME="${FILE_NAME_WITH_EXT%*.$FILE_EXTENSION}"
FILE_EXTENSION=$(echo "$FILE_NAME_WITH_EXT" | rev | cut -f 1 -d '.' | rev)
FILE_NAME_NO_EXT=$(echo "$FILE_NAME_WITH_EXT" | sed -e s/\.${FILE_EXTENSION}$//g)

#SPLIT_TO_PATH="$FILE_DIR_PATH/$FILE_NAME_NO_EXT"
SPLIT_TO_PATH="$FILE_DIR_PATH/$SPLIT_FOLDER_NAME"

mkdir "$SPLIT_TO_PATH"

# 5 seconds overlap
mp3splt -T12 -t ${SPLIT_BY_MINUTES}.00 -d "$SPLIT_TO_PATH" -O 0.5 "$FILE_REL_PATH"
cd "$SPLIT_TO_PATH"
rename 's/m_00s__/_m__to__/gi' *.mp3
rename 's/m_05s./_m./gi' *.mp3
#rename 's/_/ /gi' *.mp3
