#!/bin/bash

# https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
set -o errexit
set -o functrace
set -o nounset

SCRIPTS="$HOME/scripts"
SCRIPT_RHVOICE_FIXED="$SCRIPTS/rhvoice-fixed.sh"

if [ "$#" -lt 1 ]; then
  echo "Usage: create-abook SOURCE"
  exit
fi

function parse_extension { FILE_NAME_WITH_EXT="$1"
  echo "$FILE_NAME_WITH_EXT" | rev | cut -f 1 -d '.' | rev
}

function parse_file_name_no_ext { FILE_NAME_WITH_EXT="$1"
  EXTENSION=$(parse_extension "$FILE_NAME_WITH_EXT")
  #echo "DEBUG: parse_file_name_no_ext: EXTENSION: $EXTENSION"
  echo "$FILE_NAME_WITH_EXT" | sed -e s/\.${EXTENSION}$//g
}

SOURCE_PATH="$1"
SOURCE_PATH_NO_EXT=$(parse_file_name_no_ext "$1")
DEST_PATH="$SOURCE_PATH_NO_EXT.mp3"

(
  set -x;
  cat "$SOURCE_PATH" | "$SCRIPT_RHVOICE_FIXED" | lame -b 192 -q 0 - "$DEST_PATH"
)
