#!/bin/bash

# `sudo apt install mp3splt` required before first run

function mediainfo_readable_duration { FILE_PATH="$1"
  DURATION=$(mediainfo "$FILE_PATH" | grep Duration | head -n 1 | sed -n -e 's/^Duration[ ]*:[ ]*//p')
  echo "$DURATION"
}

SCRIPT_NAME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# human-readable conditions by qzb
source "$SCRIPT_DIR/is"

FILE_REL_PATH="$1"

if is empty "$FILE_REL_PATH"; then
  echo "Usage: $SCRIPT_NAME file_name [target_dir=./split] [split_by_minutes=10]"
  exit
fi

SPLIT_TO_PATH="$2"

SPLIT_BY_MINUTES=$3

if is empty "$SPLIT_BY_MINUTES"; then
  SPLIT_BY_MINUTES=10
fi

FILE_ABS_PATH=$(readlink -f "$FILE_REL_PATH")
FILE_DIR_PATH=$(dirname "$FILE_REL_PATH")
FILE_NAME_WITH_EXT=$(basename "$FILE_REL_PATH")

if is empty "$SPLIT_TO_PATH"; then
  SPLIT_TO_PATH="$FILE_DIR_PATH/split"
  mkdir "$SPLIT_TO_PATH"
fi

#FILE_EXTENSION="${FILE_NAME_WITH_EXT#*.}"
#FILE_NAME="${FILE_NAME_WITH_EXT%*.$FILE_EXTENSION}"
FILE_EXTENSION=$(echo "$FILE_NAME_WITH_EXT" | rev | cut -f 1 -d '.' | rev)
FILE_NAME_NO_EXT=$(echo "$FILE_NAME_WITH_EXT" | sed -e s/\.${FILE_EXTENSION}$//g)

if is not a dir "$SPLIT_TO_PATH"; then
  echo "\"$SPLIT_TO_PATH\" is not a dir"
  exit
fi

cd "$SPLIT_TO_PATH"
EXISTING_FILES=$(find -maxdepth 1 -wholename "./$FILE_NAME_NO_EXT*.$FILE_EXTENSION")

if is not empty "$EXISTING_FILES"; then
  echo "Target already have file:"
  echo -e "$EXISTING_FILES"
  exit
fi

FILE_DURATION_MS=$(mediainfo --Inform="General;%Duration%" "$FILE_ABS_PATH")
let "FILE_DURATION_S=$FILE_DURATION_MS/1000"

let "SPLIT_BY_S=SPLIT_BY_MINUTES*60"

if is le "$FILE_DURATION_S" "$SPLIT_BY_S"; then
  FILE_DURATION_READABLE=$(mediainfo_readable_duration "$FILE_ABS_PATH")
  echo "File is too short to split: $FILE_DURATION_READABLE"
  exit
fi

# 5 seconds overlap
mp3splt -T12 -t ${SPLIT_BY_MINUTES}.00 -d "$SPLIT_TO_PATH" -O 0.5 "$FILE_ABS_PATH"

cd "$SPLIT_TO_PATH"
rename 's/m_00s__/_m__to__/gi' *.mp3
rename 's/m_05s./_m./gi' *.mp3
#rename 's/_/ /gi' *.mp3
