#!/bin/bash

ALIASES_FILE=/home/d9k/.aliases

if [ -f $ALIASES_FILE ]; then
    shopt -s expand_aliases
    source $ALIASES_FILE
fi

COMMAND=$(alias "$1" | cut -d "'" -f2)

if [[ -n "$COMMAND" ]]; then
  shift # ... argument
  $COMMAND "$@"
fi
