#!/bin/bash

ALIAS="$1"

DIR="$(pwd)"

OUTPUT="$HOME/.aliases-temp"

export $ALIAS="$DIR"

if [[ -n "$ALIAS" ]]; then
  echo "export $ALIAS=\"$DIR\"" >> "$OUTPUT"
fi

echo "..."
tail "$OUTPUT"
echo

if [[ -z "$ALIAS" ]]; then
  echo "Error: Alias was not provided!"
else
  echo "Run"
  echo ". $OUTPUT"
fi
