#!/bin/bash

REPO_TYPE=$(get-repo-type)
REQUIRED_USERNAME="d9k"

if [[ -z "$REPO_TYPE" ]]; then
  echo "Repo not detected"
  exit
fi

if [ "$REPO_TYPE" == "git" ]; then

  GIT_USERNAME=$(git config --get user.name)

  if [[ "$GIT_USERNAME" != "$REQUIRED_USERNAME" ]]; then
    echo "Autocommit available for git username \"$REQUIRED_USERNAME\" only, current username is \"$GIT_USERNAME\""
    exit
  fi

  git add . &&\
    git commit

  # custom script
  push
  exit
fi

if [ "$REPO_TYPE" == "hg" ]; then
  hg add &&\
    hg commit

  hg push
  exit
fi
