#!/bin/bash
if [ -z "$1" ]; then
   	echo "no input file"
   	exit
fi

full_path=$(readlink -f "$1")
file_name=$(basename "${full_path}")

directory=$(dirname "${full_path}")

cd "$directory"
if [ ! -f "${file_name}" ]; then
   echo "file doesn't exist!"
   exit
fi


backup_file_name="${file_name}.bk"

if [[ -f "${backup_file_name}" ]]; then
  # echo "Backup ${backup_file_name} already exists"
  MAX_BACKUP_NUMBER=100
  for ((number=1; number <= ${MAX_BACKUP_NUMBER}; number++))
  {
    backup_file_name="${file_name}.bk.${number}"
    if [[ ! -f "${backup_file_name}" ]]; then
      break;
    fi
  }

  if [ "$number" -ge "$MAX_BACKUP_NUMBER" ]; then
    echo "Version overflow; Backup cannot be created"
    exit
  fi
fi

command="cp ${file_name} ${backup_file_name}"

#check_writable
if [ -w "$directory" ]; then
    eval "${command}"
else
    eval "sudo ${command}"
fi

cd /
ls -l "${directory}/${file_name}"
ls -l "${directory}/${file_name}.bk"*
