#!/bin/bash
if [ -z "$1" ]; then
   	echo "no input file"
   	exit
fi

full_path=$(readlink -f "$1")
file_name=$(basename "${full_path}")

directory=$(dirname "${full_path}")

SOURCE_IS_DIRECTORY=

cd "$directory"
if [ ! -f "${file_name}" ]; then
  if [ -d "${file_name}" ]; then
    SOURCE_IS_DIRECTORY=1
    echo "Source is directory \"${file_name}\""
  else
    echo "file doesn't exist!"
    exit
  fi
fi

backup_file_name="${file_name}.bk"

if [[ -e "${backup_file_name}" ]]; then
  # echo "Backup ${backup_file_name} already exists"
  MAX_BACKUP_NUMBER=100
  for ((number=1; number <= ${MAX_BACKUP_NUMBER}; number++))
  {
    backup_file_name="${file_name}.${number}.bk"
    if [[ ! -e "${backup_file_name}" ]]; then
      break;
    fi
  }

  if [ "$number" -ge "$MAX_BACKUP_NUMBER" ]; then
    echo "Version overflow; Backup cannot be created"
    exit
  fi
fi

command='cp -r "${file_name}" "${backup_file_name}"'

#check_writable
if [ -w "$directory" ]; then
    eval "${command}"
else
    eval "sudo ${command}"
fi

cd /
ls -l "${directory}/${file_name}"
if [[ -d "${directory}/${backup_file_name}" ]]; then
    echo "Target is directory \"${directory}/${backup_file_name}\""
    ls -l "${directory}/${backup_file_name}" 
else
    ls -l "${directory}/${file_name}.bk"
    ls -l "${directory}/${file_name}.bk".* 2>/dev/null
    ls -l "${directory}/${file_name}."*".bk" 2>/dev/null
fi
