#!/bin/bash

function echoerr {
  printf "%s\n" "$*" >&2;
}

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

COMMAND_PATH=$($SCRIPT_DIR/command-real-path "$1")

if [[ -n "$COMMAND_PATH" ]]; then
  echoerr "Found command \"$COMMAND_PATH\""
  cat "$COMMAND_PATH"
else
  echoerr "Command not found"
fi
