#!/bin/bash

# export PAGE="https://metrics.torproject.org/rs.html"

PAGE="https://youtube.com"
WINDOW_NAME="Chrome Proxy"


# --proxy-server="http://127.0.0.1:9119" \

chrome \
  --private \
  --proxy-server="socks5://127.0.0.1:1080" \
  --window-name="$WINDOW_NAME" \
  --user-data-dir="$HOME/temp/chrome-data-dir-proxy" \
  --profile-directory="Default" \
  "$PAGE"


# NOTE
# may require you to run
# `chrome --profile-directory="Default"`
# after
