#!/bin/bash

COLOR=$(set -x; gpick --pick --single --output | tr '[:upper:]' '[:lower:]')

if [[ -z "$COLOR" ]]; then
  echo "Error: color not selected!"
  exit
fi

echo "$COLOR" | xclip -selection c

echo "\"$COLOR\" was copied to clipboard"
