#!/bin/bash

# ta
SCRIPT_EDITOR="silent.sh textadept"

script_path=$1

if [[ -z "${script_path}" ]]; then
  echo "File path argument not set. Exitting"
  exit
fi

script_path="$(which ${script_path})"

if [[ ! -f "${script_path}" ]] ; then
  echo "File at ${script_path} doesn't exists. Exitting"
  exit
fi

script_path=$(readlink -f "$script_path")

echo "New script path (press ctrl+c to exit):"
read -re -p '> ' -i "${script_path}" new_script_path

set -x
cp -i "$script_path" "$new_script_path"
${SCRIPT_EDITOR} "$new_script_path"
