#!/bin/bash

docker_container_id=$1

if [[ -z "$docker_container_id" ]]; then
  echo "Container id argument is required"
  echo
  docker ps
  exit
fi

docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $1
