#!/bin/bash

#[[ -t 1 ]] && \
#    echo 'STDOUT is attached to TTY'
#
#[[ -p /dev/stdout ]] && \
#    echo 'STDOUT is attached to a pipe'
#
#[[ ! -t 1 && ! -p /dev/stdout ]] && \
#    echo 'STDOUT is attached to a redirection'
#

# https://unix.stackexchange.com/a/388462

INPUT=

if [ ! -t 0 ]; then
  echo "(pipe has data)"

  INPUT=$(< /dev/stdin)
else
  echo "(no pipe)"
  INPUT="$@"
fi

echo $INPUT
