#!/bin/bash

CURRENT_PATH="$@"

if [ ! -e "$CURRENT_PATH" ]; then
  CURRENT_PATH=$(which "$CURRENT_PATH")
  NOT_FOUND=$(echo "$CURRENT_PATH" | grep "not found")
  if [ -n "$NOT_FOUND" ]; then
    exit
  fi
fi

LAST_PATH=

while [[ "$CURRENT_PATH" != "$LAST_PATH" ]]; do
  LAST_PATH="$CURRENT_PATH"
	CURRENT_PATH=$(readlink -f "${CURRENT_PATH}")
done

echo $CURRENT_PATH

