#!/bin/bash

DIR="$(pwd)"

while [[ $(expr length "${DIR}") -gt 1 ]]; do
  #echo $DIR
  #echo $(expr length ${DIR})
  #echo

  if [[ -d "$DIR/.git" ]]; then
    echo "git"
    echo $DIR
  fi
    if [[ -d "$DIR/.hg" ]]; then
    echo "hg"
    echo $DIR
  fi
  DIR=$(dirname "$DIR")
done
