#!/bin/bash

SCRIPT_NAME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

help_exit() {
  echo "Usage: $SCRIPT_NAME commit_sha pattern"
  exit
}

if [ "$#" -lt 2 ]; then
  help_exit
fi

COMMIT=$1
shift

git diff $COMMIT..HEAD | egrep -v "^\-" | grep "^\+" | grep -B 3 -A 7 --color "$@"
