#!/bin/bash

# Meld directories comparison doesn't save files copied with `copy to right` :(

BRANCH="$1"

if [[ -z "$BRANCH" ]]; then
  BRANCH="origin/master"
fi

TEMP_DIR="$(mktemp -d -t git-compare-XXXXXXXXXX)"

trap 'rm -rf -- "$TEMP_DIR"' EXIT

#TODO corrupts current workdir too!!
#git --work-tree=${TEMP_DIR} checkout "$BRANCH" -- .
git archive "$BRANCH" | tar --extract --directory="${TEMP_DIR}"

set -x;
#G_MESSAGES_DEBUG=none

# requires
meld . ${TEMP_DIR} &>/dev/null



