#!/bin/bash

SCRIPT_NAME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

help_exit() {
  echo "Usage: $SCRIPT_NAME [current_revision] parent_revision"
  echo "  current_revision: HEAD by default"
  exit
}

set -e
# Any subsequent(*) commands which fail will cause the shell script to exit immediately

CURRENT_REV="$1"
PARENT_REV="$2"

if [[ -z "$PARENT_REV" ]]; then
  PARENT_REV="$CURRENT_REV"
  CURRENT_REV=HEAD
fi

CURRENT_HASH=$(git rev-parse $CURRENT_REV)
#RESULT="$?" && "$RESULT" && exit "$RESULT"

#RET="$?"; test $RET -ne 0 && exit $RET;

PARENT_HASH=$(git rev-parse $PARENT_REV)
#RET="$?"; test $RET -ne 0 && exit $RET;

#RESULT="$?" && "$RESULT" && exit "$RESULT"

#RESULT="$?"
#if [[ "$RESULT" != "0" ]]; then exit "$RESULT"; fi

#echo "$CURRENT_HASH"
#echo "$PARENT_HASH"

RESULT=$(git log --no-merges --oneline --pretty=tformat:"%H" | grep "^$PARENT_REV")

echo -e "$RESULT"

if [[ -z "$RESULT" ]]; then
  exit 1
fi
