#!/bin/bash

BRANCH=$(git branch --show-current)

NEW_BRANCH_SUFFIX="$1"

BACKUP_PREFIX="${BRANCH}-backup"

EXISTING_BRANCHES=$(git branch --all | grep "$BACKUP_PREFIX" | trim | sort -V)

echo -e "$EXISTING_BRANCHES"

if [[ -z "$NEW_BRANCH_SUFFIX" ]]; then
  exit
fi

PREVIOUS_BRANCH=$(echo -e "$EXISTING_BRANCHES" | tail -n 1)

PREVIOUS_BRANCH_PREFIX=$(echo "$PREVIOUS_BRANCH" | sed --regexp-extended "s/${BACKUP_PREFIX}-?//")

PREVIOUS_BRANCH_NUM=$(echo "$PREVIOUS_BRANCH_PREFIX" | grep --only-matching --no-filename --extended-regexp "^[0-9]+")

if [[ -z "$PREVIOUS_BRANCH_NUM" ]]; then
  PREVIOUS_BRANCH_NUM=0
fi

((NEW_BRANCH_NUM = $PREVIOUS_BRANCH_NUM + 1))

NEW_BRANCH="${BACKUP_PREFIX}-${NEW_BRANCH_NUM}-${NEW_BRANCH_SUFFIX}"

echo
echo "+ $NEW_BRANCH"

git branch "$NEW_BRANCH"
