#!/bin/bash

SCRIPT_NAME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

help_exit() {
  echo "Usage: $SCRIPT_NAME commit_sha search_term"
  exit
}

if [ "$#" -lt 2 ]; then
  help_exit
fi

COMMIT=$1
shift

( set -x; git --no-pager diff $COMMIT..HEAD | egrep -v "^\-" | grep "^\+" | grep --color --fixed-strings "$@")
