#!/bin/bash

REPO_URL=$(git config --get remote.origin.url)

function show_help() {
  echo -e "
Usage:  git-clone-branch-to-folder  REV_OR_BRANCH_TO_EXPORT  DEST_FOLDER

* DEST_FOLDER - must not exist

"
}

if [ "$#" -lt 2 ]; then
  show_help
  exit 1
fi

BRANCH="$1"
DEST_FOLDER="$2"

if [ -z "$REPO_URL" ]; then
  echo "Can't detect repo url"
  exit
fi

DEST_FOLDER=$(readlink -f "$DEST_FOLDER")

DEST_FOLDER_PARENT=$(dirname "$DEST_FOLDER")

#echo "$DEST_FOLDER_PARENT"

SRC_FOLDER=$(git rev-parse --show-toplevel)

git fetch origin "$BRANCH":"$BRANCH"

echo "Cloning to \"$DEST_FOLDER\""

set -x

#git clone --single-branch -b "$BRANCH" "$REPO_URL" "$DEST_FOLDER"
#git clone --single-branch --branch "$BRANCH" . "$DEST_FOLDER"

cd "$DEST_FOLDER_PARENT"
git clone --single-branch -b "$BRANCH" "$SRC_FOLDER" "$DEST_FOLDER"

cd "$DEST_FOLDER"
git config remote.origin.url "$REPO_URL"

git gc --prune

# отключено, т. к. очень медленно
#--aggressive
