#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

SCRIPT_NAME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

help_exit() {
  echo "Usage: $SCRIPT_NAME commit_sha"
  exit
}

if [ "$#" -lt 1 ]; then
  help_exit
fi

"$SCRIPT_DIR/git-backup-branch" squash

git rebase --autosquash --autostash --interactive "$@"
