#!/bin/bash

function ask_continue { action_name=$1
  if [[ -z "${action_name}" ]]; then
    action_name="move"
  fi

  # -s	        do not echo input coming from a terminal
  # -p          prompt	output the string PROMPT without a trailing newline before
  #       attempting to read
  # -r  	  	  do not allow backslashes to escape any characters
  # -n nchars	  return after reading NCHARS characters rather than waiting
  #    		for a newline,
  read -n 1 -r -p "? (Press \"y\" to ${action_name}): " input

  # new line but with stderr, escaping capture output
  echo >&2

  if [ "$input" != "Y" ] && [ "$input" != "y" ] && [ "$input" != "д" ] && [ "$input" != "Д" ]; then
    exit
  fi
  echo 1
}

SCRIPT_NAME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

help_exit() {
  echo "Usage: $SCRIPT_NAME branch_name"
  exit
}

if [ "$#" -lt 1 ]; then
  help_exit
fi

BRANCH="$1"

echo -e "Do you want to move branch \"$BRANCH\" from\n"

git log -n 1 "$BRANCH"

echo -e "\nto\n"

git log -n 1

echo

if [[ "$(ask_continue)" != "1" ]]; then
  exit;
fi

git branch -f "$BRANCH"

git checkout "$BRANCH"
