#!/bin/bash

# https://stackoverflow.com/a/16493707/1760643

SCRIPT_NAME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

show_help() {
  echo "Help: ${SCRIPT_NAME} [FILE] [REVISION] [TARGET_DIR]"
}

# Arguments count check
if [ "$#" -lt 3 ]; then
  show_help
  exit 1
fi

FILE="$1"
REVISION="$2"
TARGET_DIR=$(readlink -f "$3")


REVISION_DATE=$(git show -s --date=format:'%Y_%m_%d__%H_%M' --format="%cd" $REVISION)
REVISION_FIRST_SYMBOLS=$(echo $REVISION | head -c 8)

WORK_TREE="${TARGET_DIR}/${REVISION_DATE}__${REVISION_FIRST_SYMBOLS}"

mkdir -p "$WORK_TREE"

git show --stat "$REVISION"
echo

( set -x; git --work-tree="$WORK_TREE" checkout "$REVISION" -- "$FILE" )

echo

tree "$WORK_TREE"

TARGET_FILE_PATH="$WORK_TREE/$FILE"

ls -l "$TARGET_FILE_PATH"
