#!/bin/bash

SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Meld directories comparison doesn't save files copied with `copy to right` :(

BRANCH="$1"

if [[ -z "$BRANCH" ]]; then
  BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
fi

if [[ -z "$COMPARATOR" ]]; then
  COMPARATOR="meld"
fi

TEMP_DIR="$(mktemp -d -t git-compare-XXXXXXXXXX)"

trap 'rm -rf -- "$TEMP_DIR"' EXIT

#TODO corrupts current workdir too!!
#git --work-tree=${TEMP_DIR} checkout "$BRANCH" -- .
git archive "$BRANCH" | tar --extract --directory="${TEMP_DIR}"

set -x;
#G_MESSAGES_DEBUG=none

# requires

"${SCRIPTS_DIR}/git-rev-has-parent" > /dev/null

if [[ "$?" == "0" ]]; then
  COMPARING_WITH_PARENT=1
fi

if [[ -n "$COMPARING_WITH_PARENT" ]]; then
  echo "Compare with parent mode: target branch is on LEFT"
  ( set -x; ${COMPARATOR} ${TEMP_DIR} . &>/dev/null )
else
  ( set -x ${COMPARATOR} . ${TEMP_DIR} &>/dev/null )
fi


