#!/bin/bash

# TODO почему-то при переправлении вывода в файл/переменную без флага `--source` название ветки пропадает

BRANCH=$(git rev-parse --abbrev-ref HEAD)

ORIGIN_BRANCH="origin/$BRANCH"

ORIGIN_BRANCH_EXISTS=$(git branch --all | grep "$ORIGIN_BRANCH")

if [[ -z "$ORIGIN_BRANCH_EXISTS" ]]; then
  echo "Origin branch $ORIGIN_BRANCH doesn't exist yet"
  exit
fi

#git log --branches --source --not --remotes

git log "$ORIGIN_BRANCH..$BRANCH"
