#!/bin/bash

BRANCH_SUFFIX="$1"
BRANCH_PREFIX="$2"
SILENT_EXIT="$3"

function ask_continue { action_name=$1
  if [[ -z "${action_name}" ]]; then
    action_name="continue"
  fi

  # -s	        do not echo input coming from a terminal
  # -p          prompt	output the string PROMPT without a trailing newline before
  #       attempting to read
  # -r  	  	  do not allow backslashes to escape any characters
  # -n nchars	  return after reading NCHARS characters rather than waiting
  #    		for a newline,
  read -n 1 -r -p "(Press \"y\" to ${action_name}): " input

  # new line but with stderr, escaping capture output
  echo >&2

  if [ "$input" != "Y" ] && [ "$input" != "y" ] && [ "$input" != "д" ] && [ "$input" != "Д" ]; then
    exit
  fi
  echo 1
}

if [[ -z "$BRANCH_SUFFIX" ]]; then
  echo "Branch suffix not specified"
  exit
fi

if [[ -z "$BRANCH_PREFIX" ]]; then
  BRANCH_PREFIX="branch"
fi

BRANCH="$BRANCH_PREFIX$BRANCH_SUFFIX"

BRANCH_EXISTS=$(git branch --list --all ${BRANCH} origin/${BRANCH})

if [[ -z "$BRANCH_EXISTS" ]]; then
  if [[ -n "$SILENT_EXIT" ]]; then
    exit 1
  fi

  echo -e "Branch \"$BRANCH\" doesn't exist\n"
  if [[ "$(ask_continue 'create it')" != "1" ]]; then
    exit
  fi
  git branch "$BRANCH"
fi

git checkout "$BRANCH"

echo
git-log-graph -n 7
