#!/bin/bash

SCRIPT_NAME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

help_exit() {
  echo "Usage: $SCRIPT_NAME commit_sha"
  exit
}

if [ "$#" -lt 1 ]; then
  help_exit
fi

COMMIT=$1

#git diff $COMMIT..HEAD | \
git diff $COMMIT | \
  egrep -v "^\-" | \
  grep -E --color=always "^diff.*|^\+[[:space:]]*\/\/|^\+[[:space:]]*\/\*|^\+[[:space:]]*\*|^\+.*console.|TODO|FIXME|todo|fixme" | \
  less -r

