#!/bin/bash

DESTINATION="$1"

if [[ -z "$DESTINATION" ]]; then
  echo "Destination was not set"
  exit
fi

echo 1

STAGED_FILES=$(git diff --name-only --cached)

echo "Staged:"
echo -e "$STAGED_FILES"

echo -e "$STAGED_FILES" | xargs --max-lines=1 -I{} cp --parent {} "$DESTINATION"
#echo -e "$STAGED_FILES" | xargs --max-lines=1 -I{} echo {} "$DESTINATION"
#ls -l | xargs -I{} echo {}
