#!/bin/bash

SCRIPT_NAME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

help_exit() {
  echo "Usage: $SCRIPT_NAME commit_sha"
  exit
}

if [ "$#" -lt 1 ]; then
  help_exit
fi

git rebase --autosquash --interactive  $@
