#!/bin/bash

GREP_PATTERN="$1"

MAX_DEPTH="$2"

if [[ -z "$MAX_DEPTH" ]]; then
  MAX_DEPTH=100
fi 

# https://unix.stackexchange.com/questions/331696/removing-leading-dots-from-find-command-output-when-used-with-exec-echo-opti
# https://stackoverflow.com/questions/4210042/how-do-i-exclude-a-directory-when-using-find
# -L: follow symlinks
find \
  -L \
  -maxdepth $MAX_DEPTH \
  -printf '%P\n' \
  -not \( -path "./.git" -prune \) \
  -not \( -path "*/.git/*" -prune \) \
  -not \( -path "./node_modules" -prune \) \
  -not \( -path "*/node_modules/*" -prune \) \
  | rg  -i "$GREP_PATTERN"

# Commentend out to fix errors with xargs
# --color=always
