#!/bin/bash

GREP_PATTERN="$1"

MAX_DEPTH="$2"

if [[ -z "$MAX_DEPTH" ]]; then
  MAX_DEPTH=100
fi 

# https://unix.stackexchange.com/questions/331696/removing-leading-dots-from-find-command-output-when-used-with-exec-echo-opti
# https://stackoverflow.com/questions/4210042/how-do-i-exclude-a-directory-when-using-find
find \
  -maxdepth $MAX_DEPTH \
  -printf '%P\n' \
  | rg --color=always -i "$GREP_PATTERN"
