#!/bin/bash

wget sourceforge.net/projects/peazip/files/5.3.1/peazip_portable-5.3.1.LINUX.Qt.tar.gz
tar -xzvf peazip_portable-5.3.1.LINUX.Qt.tar.gz
sudo rm -rf /opt/peazip*
sudo mv peazip_portable-5.3.1.LINUX.Qt /opt/peazip
sudo ln -sf /opt/peazip /usr/bin/peazip