#!/bin/bash

SOURCE="$1"
TARGET="$2"

if [ -z "$SOURCE" ]; then
  echo "Usage: link-from-to SOURCE [DEST]"
  exit 1
fi

if [ -z "$TARGET" ]; then
  TARGET="."
fi

ln -s $(readlink -f "$SOURCE") "$TARGET"
