#!/bin/bash

SOURCE="$1"
TARGET="$2"

if [ -z "$SOURCE" ]; then
  echo "Usage: link-from-to SOURCE [DEST]"
  exit 1
fi

if [ -z "$TARGET" ]; then
  TARGET="."
fi

ln -s $(readlink -f "$SOURCE") "$TARGET"

if [[ $? -eq 0 ]]; then
  echo "Successfully linked '$(basename "$SOURCE")'"
  echo "  From: $SOURCE"
  echo "  To:   $TARGET"
else
  echo "Failed to create symlink" >&2
  exit 100
fi
