#!/bin/bash

SCRIPT_NAME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
TEMP_DIR="/tmp/youtube"

function echoerr {
  printf "%s\n" "$*" >&2;
}

function help_exit { EXIT_CODE="$1";
  if [[ -z "$EXIT_CODE" ]]; then
    EXIT_CODE=1
  fi

  echoerr "Usage: ${SCRIPT_NAME} [--proxy PROXY_URL] [-l|--link] [-c|--copy-to-clipboard] VIDEO_URL"
  exit "$EXIT_CODE"
}

PROXY_URL=""
LINK_MODE=0

while [[ $# -gt 0 ]]; do
    OPTION="$1"

    case "$OPTION" in
        --proxy)
            PROXY_URL="$2"
            shift # past argument
        ;;
        -l|--link)
            LINK_MODE=1
        ;;
        -m|--month)
            OUTPUT_MONTH=1
        ;;
        -c|--copy-to-clipboard)
            COPY_TO_CLIPBOARD=1
        ;;
        -h|--help)
            help_exit
        ;;
        *)
          if [[ "${OPTION:0:1}" == "-" ]]; then
            echoerr "Error: unknown option \"$OPTION\""
            help_exit
          else
            break
          fi
        ;;
    esac
    shift # past argument or value
done

# Arguments count check
if [ "$#" -lt 1 ]; then
  help_exit 1
fi

VIDEO_URL="$1"

mkdir -p "$TEMP_DIR"
cd "$TEMP_DIR"

YOUTUBE_DL_METADATA_ARGS=()
if [ -n "$PROXY_URL" ]; then
  YOUTUBE_DL_METADATA_ARGS+=(--proxy="$PROXY_URL")
fi
YOUTUBE_DL_METADATA_ARGS+=("$VIDEO_URL")

DL_METADATA_OUTPUT=$("$SCRIPT_DIR/youtube-dl-metadata" "${YOUTUBE_DL_METADATA_ARGS[@]}")

METADATA_FILE_NAME_LINE=$(echo -e "$DL_METADATA_OUTPUT" | grep --fixed-strings "Writing video metadata as JSON to")

echoerr "$METADATA_FILE_NAME_LINE"
METADATA_FILE_NAME=$(echo -e "$METADATA_FILE_NAME_LINE" | sed -e 's|^.*Writing video metadata as JSON to: ||')

if [ -z "$METADATA_FILE_NAME" ]; then
  echoerr "Error parsing metadata file name"
  exit 100
fi

if [ ! -f "$METADATA_FILE_NAME" ]; then
  echoerr "Error accessing metadata file \"$METADATA_FILE_NAME\""
  exit 200
fi

echoerr "Downloaded metadata file to \"$TEMP_DIR/$METADATA_FILE_NAME\""

YOUTUBE_VIDEO_ID=$(cat "$METADATA_FILE_NAME" | jq --raw-output ".id")
CHANNEL=$(cat "$METADATA_FILE_NAME" | jq --raw-output ".channel")
UPLOAD_DATE=$(cat "$METADATA_FILE_NAME" | jq --raw-output ".upload_date")
TITLE=$(cat "$METADATA_FILE_NAME" | jq --raw-output ".title")
UPLOAD_YEAR=$(echo $UPLOAD_DATE | cut -c 1-4)
UPLOAD_MONTH=$(echo $UPLOAD_DATE | cut -c 5-6)

YOUTUBE_VIDEO_SHORT_URL="https://youtube.com/watch?v=$YOUTUBE_VIDEO_ID"
UPLOAD_DATETIME="$UPLOAD_YEAR"
if [ -n "$OUTPUT_MONTH" ]; then
  UPLOAD_DATETIME="$UPLOAD_DATETIME.$UPLOAD_MONTH"
fi
VIDEO_TITLE="$TITLE / $CHANNEL / YT, $UPLOAD_DATETIME"

if [[ $LINK_MODE -eq 1 ]]; then
  RESULT="- :tv: [$VIDEO_TITLE]($YOUTUBE_VIDEO_SHORT_URL)"
else
  RESULT=`cat <<EOF 
## $VIDEO_TITLE

$YOUTUBE_VIDEO_SHORT_URL
EOF
`
fi

echoerr
echo -e "$RESULT"

if [[ -n "$COPY_TO_CLIPBOARD" ]]; then
  echo "$RESULT" | xclip -selection c
  echoerr ""
  echoerr "- copied to clipboard"
fi
