#!/bin/bash

# sudo apt-get install tesseract-ocr tesseract-ocr-rus

FILE_REL_PATH="$1"

if [[ -z "$FILE_REL_PATH" ]]; then
  echo "picture file name required"
  exit
fi

DPI="$2"

if [[ -z "$DPI" ]]; then
  DPI=70
fi

FILE_DIR_PATH=$(dirname "$FILE_REL_PATH")
FILE_NAME_WITH_EXT=$(basename "$FILE_REL_PATH")

FILE_EXTENSION=$(echo "$FILE_NAME_WITH_EXT" | rev | cut -f 1 -d '.' | rev)
FILE_NAME_NO_EXT=$(echo "$FILE_NAME_WITH_EXT" | sed -e s/\.${FILE_EXTENSION}$//g)

# TARGET_PATH="${FILE_DIR_PATH}/${FILE_NAME_NO_EXT}.mp3"
 
OUTPUT_FILE="$FILE_DIR_PATH/$FILE_NAME_NO_EXT.txt"
OUTPUT_FILE_ABS=$(readlink -f "$OUTPUT_FILE")

if [ -f "$OUTPUT_FILE_ABS" ]; then
  echo "Warning! Output text file $OUTPUT_FILE_ABS already exists! Skipping OCR"
else  
  (
    set -x
    cd "$FILE_DIR_PATH"
    tesseract "$FILE_REL_PATH" "$FILE_NAME_NO_EXT" -l eng+rus --dpi $DPI
  )
  echo "Output:"
  echo "$OUTPUT_FILE_ABS"
fi

if [ -n "$EDITOR" ]; then
  set -x
  $EDITOR "$OUTPUT_FILE"
fi
