#!/bin/bash

SCRIPT_DIR=$(dirname "$0")

#TODO
#MIN_LETTERS_LENGTH=18
#MAX_LETTERS_LENGTH=20


${SCRIPT_DIR}/res/word-list-by-sindresorhus/dl-words-if-not-exists.sh 1>&2

function one_password {

  WORDS=$(powershuf \
    -n 4 \
    --file $SCRIPT_DIR/res/word-list-by-sindresorhus/words.txt)

  PASS_LETTERS=$( \
    echo "$WORDS" | \
    `#uppercase` sed 's/./\u&/' | \
    `#join` sed -z 's/\n//g'\
  )

  #PASS_NUMBERS=$(\
  #  shuf -i 0-9999 -n 1 | \
  #  `# pad with zeros` awk '{ printf("%04d\n", $1) }' \
  #)

  echo "${PASS_LETTERS}${PASS_NUMBERS}"
}

for i in {1..20}; do
  one_password;
done
