#!/bin/bash

PASS_STORE_DIR="$HOME/.password-store"
LINES_NUM=10

cd $PASS_STORE_DIR


RESULTS=$( \
  find -type f -printf '%P\n' -iname "*.gpg" \
    | grep -P -v "^\." \
    | grep -P -v "^old\/" \
    | sed -E 's/\.gpg$//' \
    | grep -i "$1" \
    | sort
)

# echo $RESULTS

shift 1

for PATTERN in "$@"; do
  RESULTS=$(echo -n "$RESULTS" | grep -i "$PATTERN")
done


RESULTS=$(echo -n "$RESULTS" | head -n "$LINES_NUM")


if [[ -z "$RESULTS" ]]; then
  echo "No results! Exitting"
  exit 1
fi

RESULT=$(echo -n "$RESULTS" | grep -P -v "\.info$" | head -n 1)

REST_RESULTS_TEXT=$(echo -n "$RESULTS")
if [[ -n "$RESULT" ]]; then
  REST_RESULTS_TEXT=$(echo -n "$RESULTS" | grep -v "$RESULT" )
fi

if [[ -n "$REST_RESULTS_TEXT" ]]; then
  echo "## Also found"
  echo
  echo -n "$REST_RESULTS_TEXT" | sed -E 's/^/- /'
  echo
fi

RESULT_INFO="$RESULT.info"

if [[ -f "$RESULT_INFO.gpg" ]]; then
  echo
  echo "## \`$RESULT_INFO\`"
  echo
  echo "\`\`\`"
  pass "$RESULT_INFO"
  echo "\`\`\`"
fi

if [[ -n "$RESULT" ]]; then
  echo
  echo "## \`$RESULT\`"
  echo
  echo "\`\`\`"

  pass "$RESULT"
  echo "\`\`\`"

  echo
  pass -c "$RESULT"
fi


