#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

PASSWORDS=$($SCRIPT_DIR/password-generator "$@")
# echo -e "$RESULT"

echo -e "$PASSWORDS" | while read LINE ; do
   $SCRIPT_DIR/google-translate.py -s "en" -d "ru" "$LINE"
   echo
done
