#!/bin/bash

SCRIPT_DIR=$(dirname "$0")

ROWS_COUNT="$1"

if [[ -z "$ROWS_COUNT" ]]; then
  ROWS_COUNT=6
fi

WORDS_IN_ROW=4

#TODO
#MIN_LETTERS_LENGTH=18
#MAX_LETTERS_LENGTH=20


${SCRIPT_DIR}/res/word-list-by-sindresorhus/dl-words-if-not-exists.sh 1>&2

function one_row {

  WORDS=$(powershuf \
    -n "$WORDS_IN_ROW" \
    --file $SCRIPT_DIR/res/word-list-by-sindresorhus/words.txt)

  PASS_LETTERS=$( \
    echo "$WORDS" | \
    `#uppercase` sed 's/./\u&/' | \
    `#join` sed -z 's/\n/. /g'\

    #`#uppercase` sed 's/./\u&/' | \
    #`#join` sed -z 's/\n//g'\
  )

  #PASS_NUMBERS=$(\
  #  shuf -i 0-9999 -n 1 | \
  #  `# pad with zeros` awk '{ printf("%04d\n", $1) }' \
  #)

  echo "${PASS_LETTERS}${PASS_NUMBERS}"
}

for i in $( eval echo {1.."$ROWS_COUNT"} ); do
  one_row;
done
