#!/bin/bash

REPO_TYPE=$(get-repo-type)

#args_parse() {
#  while [[ $# > 0 ]] ; do
#    case "$1" in
#      -s)
#        varg1=${2}
#        #shift
#        ;;
#      #--arg2)
#        #varg2=true
#        #;;
#    esac
#    shift
#  done
#}
#
#args_parse "$@"

function ask_continue { action_name=$1
  if [[ -z "${action_name}" ]]; then
    action_name="continue"
  fi

  # -s	        do not echo input coming from a terminal
  # -p          prompt	output the string PROMPT without a trailing newline before
  #       attempting to read
  # -r  	  	  do not allow backslashes to escape any characters
  # -n nchars	  return after reading NCHARS characters rather than waiting
  #    		for a newline,
  read -n 1 -r -p "Press \"y\" to ${action_name}: " input

  # new line but with stderr, escaping capture output
  echo >&2

  if [ "$input" != "Y" ] && [ "$input" != "y" ] && [ "$input" != "д" ] && [ "$input" != "Д" ]; then
    exit
  fi
  echo 1
}

if [[ -z "$REPO_TYPE" ]]; then
  echo "Repo not detected"
  exit
fi

if [ "$REPO_TYPE" == "git" ]; then

  echo
  echo "Current git branch:"
  echo "  $(git-current-branch)"
  echo

  COMMITS_TO_PUSH="$(git-to-push)"

  if [[ -z "$COMMITS_TO_PUSH" ]]; then
    echo "No new commits to push"
    exit
  fi

  echo "# New commits:"
  echo
  echo -e "${COMMITS_TO_PUSH}"

  echo

  if [[ "$(ask_continue push)" != "1" ]]; then
    exit;
  fi

  echo

  set -x
  #git push
  # only current branch
  git push origin HEAD
  git pull
  git push origin --tags
  exit
fi

if [ "$REPO_TYPE" == "hg" ]; then
  echo "Hg repo"
  hg push
  exit
fi
