#!/bin/bash

STORE_LAST_FILE_PATH=$HOME/.rename_file_last

FILE_PATH="$1"

if [[ -z "${FILE_PATH}" ]]; then
  if [[ -f "${STORE_LAST_FILE_PATH}" ]]; then
    FILE_PATH=$(cat $STORE_LAST_FILE_PATH)
  fi
fi

if [[ -z "${FILE_PATH}" ]]; then
  echo "File path argument not set. Exitting"
  exit
fi

if [[ ! -f "${FILE_PATH}" ]] && [[ ! -d "${FILE_PATH}" ]]; then
  echo "File at ${FILE_PATH} doesn't exists. Exitting"
  exit
fi

echo
if [[ -d "${FILE_PATH}" ]]; then
  echo "\"${FILE_PATH}\" is a directory. Contents:"
fi
ls -l "${FILE_PATH}"
echo

FILE_PATH=$(readlink -f "$FILE_PATH")

echo "New file path (press ctrl+c to exit):"
read -re -p '> ' -i "${FILE_PATH}" NEW_FILE_PATH

set -x ;
mv -i "$FILE_PATH" "$NEW_FILE_PATH"

{ set +x; } 2>/dev/null

# source it to use $RENAME_LAST_TO variable:
# at .bashrc
#
# alias -- rename-file='source $HOME/scripts/rename-file'

echo "$NEW_FILE_PATH" > $STORE_LAST_FILE_PATH

echo "New path:"
echo "$NEW_FILE_PATH"

# add this to .bashrc and call rename_file to save last file name to variable
#
# function rename_file() {
#   export RENAME_LAST_TO=
#   OUTPUT=$($HOME/scripts/rename-file $@ | tee /dev/tty)
#   BEFORE_LAST=$(echo $OUTPUT | tail -n 2 | head -n 1)
#   LAST=$(echo $OUTPUT | tail -n 1)
#   if [[ "$BEFORE_LAST" == "New path:" ]]; then
#     export RENAME_LAST_TO="$LAST"
#   fi
# }

