#!/bin/bash

# https://superuser.com/questions/1310825/how-to-remove-old-version-of-installed-snaps

# Removes old revisions of snaps
# CLOSE ALL SNAPS BEFORE RUNNING THIS

# -e: stop on error
# -u: using unset var is error
set -eu

LANG=C snap list --all | awk '/disabled/{print $1, $3}' |
    while read snapname revision; do
       sudo snap remove "$snapname" --revision="$revision"
    done
