#!/bin/bash

# https://superuser.com/questions/231002/how-can-i-search-within-the-output-buffer-of-a-tmux-shell
LINE=$(\
  tmux capture-pane -pS -300 \
  | rg -v "^#" \
  | rg -v "^> hl" \
  | rg -v "^[\s]*$" \
  | tac \
  | fzf \
)

echo "$LINE" | xclip -selection c


