#!/bin/bash

# ripgrep required!
# https://github.com/BurntSushi/ripgrep

# Use Ctrl-C to exit

export INFO_PREFIX="$@"

# Any subsequent(*) commands which fail will cause the shell script to exit immediately
set -e

# https://superuser.com/questions/231002/how-can-i-search-within-the-output-buffer-of-a-tmux-shell
LINE=$(\
  tmux capture-pane -pS -300 \
  | rg -v "^#" \
  | rg -v "^> hl" \
  | rg -v "^[\s]*$" \
  | tac \
  | fzf \
    --info-command='echo "${INFO_PREFIX}[Ctrl-C] to exit. Select line to copy, press [Enter]. After copy selector will rerun automatically."'  \
  \
)

set +e

LINE=$(echo "$LINE" | rg --passthrough --replace "" "^> " | trim)

# EXIT_CODE="$#"

if [[ -z "$LINE" ]]; then
  exit
fi

printf "%s" "$LINE" | xclip -selection c

# echo "$EXIT_CODE"

# restart to copy another line
$0 "Copied « $LINE ».    "
