#!/bin/bash

youtube-dl \
  --no-playlist \
  -f 'bestvideo[ext=mp4][container=mp4_dash][height<=1440]+bestaudio[ext=m4a]/bestvideo+bestaudio' \
  --merge-output-format mp4 \
  --write-thumbnail \
  --write-auto-subs \
  --write-info-json \
  --convert-thumbnails jpg \
  --sub-format srt \
  --convert-subtitles srt \
  "$@"
