#!/bin/bash

youtube-dl -F $@

cat << ENDMESSAGE

Example download:
   youtube-dl -f 137+141
Example stream (SMplayer: Ctrl+I -> Options for MPlayer/mpv -> Options):
   --ytdl-format=137+141"
ENDMESSAGE
