#!/bin/bash

# Edit Zeuslap monitor brightness. Fails somehow. Only 0 and 100 input values are supported
#
# 1 <= 90
# 2 <= 100=0x64, 1023=0x3ff
# # ? ? ? ? ?
# 8 <= 0
# 9 <= 10
# 10 <= 20, 1024=0x400

BRIGHT_SCRIPT="$HOME/scripts/bright"
BACKLIGHT_GET_SCRIPT="$HOME/scripts/win/backlight-get"

ARG="$1"

DEV="dev:/dev/i2c-6"

# https://askubuntu.com/a/1181157/156571
# https://github.com/ddccontrol/ddccontrol/issues/20

function echoerr {
  printf "%s\n" "$*" >&2;
}

if [[ -z "$ARG" ]]; then
  echoerr "Backlight brighness argument not provided! Examples: +5 / -1 / 75"
  exit 1;
fi

ARG_BEGIN="${ARG:0:1}"

if [ "$ARG_BEGIN" = "+" ]; then
  ddccontrol -r 0x10 -W "$ARG" "$DEV"
  # "$BRIGHT_SCRIPT" 1
elif [ "$ARG_BEGIN" = "-" ]; then
  BACKLIGHT_VALUE=$("$BACKLIGHT_GET_SCRIPT")

  if [ $BACKLIGHT_VALUE -gt 1 ]; then
    # ddccontrol -r 0x10 -W "$ARG" "$DEV"
    ddccontrol -f -r 0x10 -W "$ARG" "$DEV"
  else
    # "$BRIGHT_SCRIPT" -
    :
  fi
else
  # "$BRIGHT_SCRIPT" 1
  # ddccontrol -r 0x10 -w "$ARG" "$DEV"
  ddccontrol -f -r 0x10 -w "$ARG" "$DEV"
fi
